AllCops:
  Exclude:
    - Guardfile
    - vendor/**/*
    - lib/ogre/skeletons/**/*
    - tmp/**/*
Metrics/AbcSize:
  Enabled: false
Metrics/LineLength:
  Max: 120
Metrics/MethodLength:
  Max: 50
Style/SpecialGlobalVars:
  Enabled: false
Style/FileName:
  Enabled: false
Style/GuardClause:
  Enabled: false
